rosbag_to_images_node:
  ros__parameters:
    input_dir: "./"
    output_dir: "./rosbag_images/"
    image_topic: "/camera/image_raw"

    frame_interval: 30
    undistort: true
    convert_to_bev: false # undistort must also be true if the raw image is used
    print_status_interval: 100
